/* 	Copyright (c) [2020]-[2021] Ittiam Systems Pvt. Ltd.
   All rights reserved.

   Redistribution and use in source and binary forms, with or without
   modification, are permitted (subject to the limitations in the
   disclaimer below) provided that the following conditions are met:
   •	Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
   •	Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
   •	Neither the names of Dolby Laboratories, Inc. (or its affiliates),
   Ittiam Systems Pvt. Ltd. nor the names of its contributors may be used
   to endorse or promote products derived from this software without
   specific prior written permission.

   NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED
   BY THIS LICENSE. YOUR USE OF THE SOFTWARE MAY REQUIRE ADDITIONAL PATENT
   LICENSE(S) BY THIRD PARTIES, INCLUDING, WITHOUT LIMITATION, DOLBY
   LABORATORIES, INC. OR ANY OF ITS AFFILIATES. THIS SOFTWARE IS PROVIDED
   BY ITTIAM SYSTEMS LTD. AND ITS CONTRIBUTORS "AS IS" AND ANY EXPRESS OR
   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
   IN NO EVENT SHALL ITTIAM SYSTEMS LTD OR ITS CONTRIBUTORS BE LIABLE FOR
   ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
   DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
   OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
   HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
   STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
   IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
   POSSIBILITY OF SUCH DAMAGE.
---------------------------------------------------------------
*/

#ifndef IMPEGHD_ERROR_CODES_H
#define IMPEGHD_ERROR_CODES_H

#define IA_MPEGH_DEC_NO_ERROR 0x00000000

/*****************************************************************************/
/* Class 0: API Errors                                                       */
/*****************************************************************************/

/* Fatal Errors */

#define IA_MPEGH_DEC_API_FATAL_MEM_ALLOC 0xFFFF8000

/*****************************************************************************/
/* Class 1: Configuration Errors                                             */
/*****************************************************************************/

/* Non Fatal Errors */
#define IA_MPEGH_DEC_CONFIG_NONFATAL_INVALID_PCM_WDSZ 0x00000800
#define IA_MPEGH_DEC_CONFIG_NONFATAL_INVALID_TARGET_LOUDNESS 0x00000801
#define IA_MPEGH_DEC_CONFIG_NONFATAL_INVALID_EFFECT_TYPE 0x00000802
#define IA_MPEGH_DEC_CONFIG_NONFATAL_INVALID_CICP_INDEX 0x00000803
#define IA_MPEGH_DEC_CONFIG_NONFATAL_INVALID_PRESET_ID 0x00000804

/*****************************************************************************/
/* Class 2: Initialization Errors                                            */
/*****************************************************************************/

/* Non Fatal Errors */
#define IA_MPEGH_DEC_INIT_NONFATAL_INSUFFICIENT_INPUT_BYTES 0x00001000
#define IA_MPEGH_DEC_INIT_NONFATAL_INSUFFICIENT_EI_BYTES 0x00001001
#define IA_MPEGH_DEC_INIT_NONFATAL_INSUFFICIENT_LSI_BYTES 0x00001002
#define IA_MPEGH_DEC_INIT_NONFATAL_INSUFFICIENT_BRIR_BYTES 0x00001003
#define IA_MPEGH_DEC_INIT_NONFATAL_INVALID_RESAMPLE_RATIO 0x00001004
#define IA_MPEGH_DEC_INIT_NONFATAL_INSUFFICIENT_MAE_BYTES 0x00001005

// DRC
#define IA_MPEGD_DRC_INIT_NONFATAL_INSUFFICIENT_BITS 0x00001100
#define IA_MPEGD_DRC_INIT_NONFATAL_UNEXPECTED_ERROR 0x00001101
#define IA_MPEGD_DRC_INIT_NONFATAL_PARAM_ERROR 0x00001102
#define IA_MPEGD_DRC_INIT_NONFATAL_UNSUPPORTED_CH_GROUPS 0x00001103
#define IA_MPEGD_DRC_INIT_NONFATAL_COEFF_MAX_EXCEEDED 0x00001104
#define IA_MPEGD_DRC_INIT_NONFATAL_SEL_PROCESS_INIT_FAIL 0x00001105
#define IA_MPEGD_DRC_INIT_NONFATAL_UNSUPPORTED_DUCKING_SEQUENCE 0x00001106
#define IA_MPEGD_DRC_INIT_NONFATAL_DRC_INSTR_MAX_EXCEEDED 0x00001107

// HOA
#define IA_MPEGH_HOA_INIT_NONFATAL_RENDERER_INIT_FAILED 0x00001200
#define IA_MPEGH_HOA_INIT_NONFATAL_INVALID_HOA_ORDER 0x00001201
#define IA_MPEGH_HOA_INIT_NONFATAL_INVALID_QUANT 0x00001202
#define IA_MPEGH_HOA_INIT_NONFATAL_INVALID_FRAME_SIZE 0x00001203
#define IA_MPEGH_HOA_INIT_NONFATAL_INVALID_MATRIX 0x00001204
#define IA_MPEGH_HOA_INIT_NONFATAL_INVALID_TRANSPORT_CHANNEL 0x00001205
#define IA_MPEGH_HOA_INIT_NONFATAL_INVALID_SUBBAND_CFG 0x00001206
#define IA_MPEGH_HOA_INIT_NONFATAL_INVALID_BIT_SIZE 0x00001207
#define IA_MPEGH_HOA_INIT_NONFATAL_MATRIX_MISMATCH 0x00001208
#define IA_MPEGH_HOA_INIT_NONFATAL_INVALID_TYPE 0x00001209
#define IA_MPEGH_HOA_INIT_NONFATAL_SPHERICAL_WAVE_MODEL_NOT_IMPLEMENTED 0x0000120A
#define IA_MPEGH_HOA_INIT_NONFATAL_SPACE_POSITION_INIT_FAILED 0x0000120B

/* Fatal Errors */
// core coder
#define IA_MPEGH_DEC_INIT_FATAL_DEC_INIT_FAIL 0xFFFF9000
#define IA_MPEGH_DEC_INIT_FATAL_STREAM_CHAN_GT_MAX 0xFFFF9001
#define IA_MPEGH_DEC_INIT_FATAL_SAMP_FREQ_NOT_SUPPORTED 0xFFFF9002
#define IA_MPEGH_DEC_INIT_FATAL_RECEIVER_COMP_DELAY 0xFFFF9003
#define IA_MPEGH_DEC_INIT_FATAL_INVALID_FILLBYTE 0xFFFF9004
#define IA_MPEGH_DEC_INIT_FATAL_3DACONFIG_DATA_NOT_FOUND 0xFFFF9005
#define IA_MPEGH_DEC_INIT_FATAL_UNSUPPORTED_CORECODER_FRAMELENGTH_IDX 0xFFFF9006
#define IA_MPEGH_DEC_INIT_FATAL_INVALID_CICP_SPKR_INDEX 0xFFFF9007
#define IA_MPEGH_DEC_INIT_FATAL_WRONG_WIN_SEQ 0xFFFF9008
#define IA_MPEGH_DEC_INIT_FATAL_UNSUPPORTED_ASI_NUM_GROUP 0xFFFF9009
#define IA_MPEGH_DEC_INIT_FATAL_UNSUPPORTED_FRAME_LENGTH 0xFFFF900A
#define IA_MPEGH_DEC_INIT_FATAL_UNSUPPORTED_ASI_NUM_SWITCH_GROUPS 0xFFFF900B
#define IA_MPEGH_DEC_INIT_FATAL_UNSUPPORTED_ASI_NUM_GROUPS_PRESETS 0xFFFF900C
#define IA_MPEGH_DEC_INIT_FATAL_MHAS_SYNCWORD_MISMATCH 0xFFFF900D
#define IA_MPEGH_DEC_INIT_FATAL_MAX_CONF_EXT_EXCEEDED 0xFFFF900E
#define IA_MPEGH_DEC_INIT_FATAL_MAX_NUM_SPKS_EXCEEDED 0xFFFF900F
#define IA_MPEGH_DEC_INIT_FATAL_ERROR 0xFFFF9010
#define IA_MPEGH_DEC_INIT_FATAL_CONFIG_EXT_LEN_EXCEEDED 0xFFFF9011
#define IA_MPEGH_DEC_INIT_FATAL_UNEXPECTED_ERROR 0xFFFF9012
#define IA_MPEGH_DEC_INIT_FATAL_UNSUPPORTED_NUM_EARCONS 0xFFFF9013
#define IA_MPEGH_DEC_INIT_FATAL_UNSUPPORTED_ASI_NUM_DESCRIPTION_BLOCKS 0xFFFF9014
#define IA_MPEGH_DEC_INIT_FATAL_UNSUPPORTED_ASI_NUM_DESCRIPTION_LANGUAGES 0xFFFF9015
#define IA_MPEGH_DEC_INIT_FATAL_UNSUPPORTED_CICP_LAYOUT_INDEX 0xFFFF9016
#define IA_MPEGH_DEC_INIT_FATAL_UNSUPPORTED_NUM_PCM_SIG 0xFFFF9017
#define IA_MPEGH_DEC_INIT_FATAL_UNSUPPORTED_ILD_IDX 0xFFFF9018
#define IA_MPEGH_DEC_INIT_FATAL_NULL_PTR_PERSIST_MEM 0xFFFF9019
#define IA_MPEGH_DEC_INIT_FATAL_MAX_NUM_SIGNALGROUPS_EXCEEDED 0xFFFF901A
#define IA_MPEGH_DEC_INIT_FATAL_UNSUPPORTED_MPEGH_PROFILE 0xFFFF901B
#define IA_MPEGH_DEC_INIT_FATAL_INVALID_PROFILE_CONFIG 0xFFFF901C
#define IA_MPEGH_DEC_INIT_FATAL_INVALID_CH_MASK_LFE 0xFFFF901D
#define IA_MPEGH_DEC_INIT_FATAL_INVALID_LPD_MODE 0xFFFF901E
#define IA_MPEGH_DEC_INIT_FATAL_INVALID_EL_ANG_IDX 0xFFFF901F
#define IA_MPEGH_DEC_INIT_FATAL_INVALID_AZ_ANG_IDX 0xFFFF9020
#define IA_MPEGH_DEC_INIT_FATAL_INVALID_IGF_ALL_ZERO 0xFFFF9021
#define IA_MPEGH_DEC_INIT_FATAL_INVALID_FAC_DATA_PRES 0xFFFF9022
#define IA_MPEGH_DEC_INIT_FATAL_INVALID_SHORT_FAC_FLAG 0xFFFF9023
#define IA_MPEGH_DEC_INIT_FATAL_INVALID_MCT_ENTRIES 0xFFFF9024
#define IA_MPEGH_DEC_INIT_FATAL_INVALID_CH_PAIR_IDX 0xFFFF9025
#define IA_MPEGH_DEC_INIT_FATAL_INVALID_DMX_CONF_TYPE 0xFFFF9026
#define IA_MPEGH_DEC_INIT_FATAL_INVALID_DMX_TYPE 0xFFFF9027
#define IA_MPEGH_DEC_INIT_FATAL_INVALID_DMX_ID 0xFFFF9028
#define IA_MPEGH_DEC_INIT_FATAL_INVALID_SPK_DIST 0xFFFF9029
#define IA_MPEGH_DEC_INIT_FATAL_UNSUPPORTED_CICP_SPK_INDEX 0xFFFF902A
#define IA_MPEGH_DEC_INIT_FATAL_UNSUPPORTED_EXT_ELEM_CONFIG 0xFFFF902B
#define IA_MPEGH_DEC_INIT_FATAL_AUD_PREROLL_PARSING_FAILED 0xFFFF902C
#define IA_MPEGH_DEC_INIT_FATAL_INVALID_DELTA_TIME 0xFFFF902D
#define IA_MPEGH_DEC_INIT_FATAL_ASI_PARSE_FAIL 0xFFFF902E
#define IA_MPEGH_DEC_INIT_FATAL_ASI_PRESET_GRP_DEF_CONFIG_FAIL 0xFFFF902F
#define IA_MPEGH_DEC_INIT_FATAL_ASI_PRESET_GRP_DEF_EXT_CONFIG_FAIL 0xFFFF9030
#define IA_MPEGH_DEC_INIT_FATAL_INVALID_GRP_ID 0xFFFF9031
#define IA_MPEGH_DEC_INIT_FATAL_COMP_PRED_NOT_SUPPORTED 0xFFFF9032
#define IA_MPEGH_DEC_INIT_FATAL_INVALID_PR_GRP_NUM_COND 0xFFFF9033
#define IA_MPEGD_DEC_INIT_FATAL_INVALID_CONFIG_FOR_LC_PROFILE 0xFFFF9034
#define IA_MPEGH_DEC_INIT_FATAL_INVALID_NUM_DM_ID_GRP_PR_EXT 0xFFFF9035
#define IA_MPEGH_DEC_INIT_FATAL_INVALID_NUM_WIRE_OUTS 0xFFFF9036
#define IA_MPEGD_DEC_INIT_FATAL_INVALID_SHIFTED_CH 0xFFFF9037
#define IA_MPEGH_DEC_INIT_FATAL_INVALID_MAX_SFB 0xFFFF9038
#define IA_MPEGH_DEC_INIT_FATAL_INVALID_ASI_PARAM 0xFFFF9039
#define IA_MPEGH_DEC_INIT_FATAL_INVALID_CONFIG_FOR_NUM_CH 0xFFFF903A
#define IA_MPEGH_DEC_INIT_FATAL_UNSUPPORTED_SIG_GROUP_TYPE 0xFFFF903B

// DRC
#define IA_MPEGD_DRC_INIT_FATAL_CH_GROUP_COUNT_EXCEEDED 0xFFFF9100
#define IA_MPEGD_DRC_INIT_FATAL_INVALID_GAIN_SET_INDEX 0xFFFF9101
#define IA_MPEGD_DRC_INIT_FATAL_UNSUPPORTED_METHOD_DEFINITION 0xFFFF9102
#define IA_MPEGD_DRC_INIT_FATAL_UNEXPECTED_ERROR 0xFFFF9103
#define IA_MPEGD_DRC_INIT_FATAL_UNSUPPORTED_SAMP_FREQ 0xFFFF9104
#define IA_MPEGD_DRC_INIT_FATAL_UNSUPPORTED_FRAME_SIZE 0xFFFF9105
#define IA_MPEGD_DRC_INIT_FATAL_UNSUPPORTED_CH_COUNT 0xFFFF9106
#define IA_MPEGD_DRC_INIT_FATAL_INVALID_DELTA_TMIN 0xFFFF9107
#define IA_MPEGD_DRC_INIT_FATAL_UNSUPPORTED_DELAY_MODE 0xFFFF9108
#define IA_MPEGD_DRC_INIT_FATAL_UNSUPPORTED_DELAY_SAMPLES 0xFFFF9109
#define IA_MPEGD_DRC_INIT_FATAL_UNSUPPORTED_SUBBAND_DOMAIN_MODE 0xFFFF910A
#define IA_MPEGD_DRC_INIT_FATAL_UNSUPPORTED_NUM_SUBBAND 0xFFFF910B
#define IA_MPEGD_DRC_INIT_FATAL_INVALID_DRC_PARAM_FOR_LC_PROFILE 0xFFFF910C

// HOA
#define IA_MPEGH_HOA_INIT_FATAL_INVALID_VIDX 0xFFFF9200
#define IA_MPEGH_HOA_INIT_FATAL_RENDER_MATRIX_INIT_FAILED 0xFFFF9201
#define IA_MPEGH_HOA_INIT_FATAL_RENDER_INIT_FAILED 0xFFFF9202
#define IA_MPEGH_HOA_INIT_FATAL_INVALID_FRAME_LENGTH_INDICATOR 0xFFFF9203
#define IA_MPEGH_HOA_INIT_FATAL_INVALID_MATRIX_SELECTED 0xFFFF9204
#define IA_MPEGH_HOA_INIT_FATAL_INVALID_HOA_CHANNELS 0xFFFF9205
#define IA_MPEGH_HOA_INIT_FATAL_INVALID_ACTIVE_DIRS_IDS 0xFFFF9206
#define IA_MPEGH_HOA_INIT_FATAL_INVALID_MIN_AMB_ORDER 0xFFFF9207
#define IA_MPEGH_HOA_INIT_FATAL_INVALID_VEC_LENGTH 0xFFFF9208
#define IA_MPEGH_HOA_INIT_FATAL_INVALID_DIFF_ORDER 0xFFFF9209
#define IA_MPEGH_HOA_INIT_FATAL_INVALID_NUM_VQ_ELE_BITS 0xFFFF920A
#define IA_MPEGH_HOA_INIT_FATAL_INVALID_HOA_IND_FLG 0xFFFF920B
#define IA_MPEGH_HOA_INIT_FATAL_INVALID_HOA_NBITSQ 0xFFFF920C
#define IA_MPEGH_HOA_INIT_FATAL_INVALID_AMB_COEF_TRANS_STATE 0xFFFF920D
#define IA_MPEGH_HOA_INIT_FATAL_INVALID_AMB_COEF_IDX 0xFFFF920E
#define IA_MPEGH_HOA_INIT_FATAL_INVALID_VVEC_IDX 0xFFFF920F
#define IA_MPEGH_HOA_INIT_FATAL_INVALID_SPARSE_ORD 0xFFFF9210
#define IA_MPEGH_HOA_INIT_FATAL_NFC_NOT_ALLOWED 0xFFFF9211
#define IA_MPEGH_HOA_INIT_FATAL_INVALID_CONFIG_LC_PROFILE 0xFFFF9212

// BINAURAL
#define IA_MPEGH_BINAURAL_INIT_FATAL_INIT_FAIL 0xFFFF9300
#define IA_MPEGH_BINAURAL_INIT_FATAL_UNSUPPORTED_BLOCK_LENGTH 0xFFFF9301

// Format Converter
#define IA_MPEGH_FORMAT_CONV_INIT_FATAL_INVALID_PARAM 0xFFFF9400
#define IA_MPEGH_FORMAT_CONV_INIT_FATAL_INIT_FAIL 0xFFFF9401
#define IA_MPEGH_FORMAT_CONV_INIT_FATAL_INVALID_CHANNEL_NUM 0xFFFF9402
#define IA_MPEGH_FORMAT_CONV_INIT_FATAL_INVALID_CICP_IDX 0xFFFF9403
#define IA_MPEGH_FORMAT_CONV_INIT_FATAL_INVALID_PRECISION_LVL 0xFFFF9404
#define IA_MPEGH_FORMAT_CONV_INIT_FATAL_INVALID_GAIN_TABLE_SIZE 0xFFFF9405
#define IA_MPEGH_FORMAT_CONV_INIT_FATAL_UNSUPPORTED_SPK_LAYOUT 0xFFFF9406
#define IA_MPEGH_FORMAT_CONV_INIT_FATAL_NO_COMP_TMPLT 0xFFFF9407
#define IA_MPEGH_FORMAT_CONV_INIT_FATAL_INVALID_NUM_CONFS 0xFFFF9408
#define IA_MPEGH_FORMAT_CONV_INIT_FATAL_INVALID_NUM_EQS 0xFFFF9409
#define IA_MPEGH_FORMAT_CONV_INIT_FATAL_INVALID_EQ_CONF 0xFFFF940A

// OAM
#define IA_MPEGH_OAM_INIT_FATAL_UNSUPPORTED_NUM_OBJS 0xFFFF9500

// INTERFACES
#define IA_MPEGH_EI_INIT_FATAL_UNSUPPORTED_INTRCTN_MODE 0xFFFF9600
#define IA_MPEGH_EI_INIT_FATAL_UNSUPPORTED_NUM_GRPS 0xFFFF9601
#define IA_MPEGH_EI_INIT_FATAL_INVALID_ID 0xFFFF9602
#define IA_MPEGH_EI_INIT_FATAL_INVALID_CHANGE_POSITION 0xFFFF9603
#define IA_MPEGH_EI_INIT_FATAL_INVALID_CHANGE_GAIN 0xFFFF9604

// Class 3: Execution Errors

// Non Fatal Errors
#define IA_MPEGH_DEC_EXE_NONFATAL_INSUFFICIENT_INPUT_BYTES 0x00001800
#define IA_MPEGH_DEC_EXE_NONFATAL_INSUFFICIENT_SD_BYTES 0x00001801
#define IA_MPEGH_DEC_EXE_NONFATAL_INSUFFICIENT_HOA_BYTES 0x00001802
#define IA_MPEGH_DEC_EXE_NONFATAL_INSUFFICIENT_METADATA_BYTES 0x00001803

// Fatal Errors
#define IA_MPEGH_DEC_EXE_FATAL_ASCPARSER_MAX_DMX_MATRICES_PER_ID_EXCEEDED 0xFFFF9800
#define IA_MPEGH_DEC_EXE_FATAL_UNSUPPORTED_WINDOW_LEN 0xFFFF9801
#define IA_MPEGH_DEC_EXE_FATAL_UNSUPPORTED_WINDOW_SHAPE 0xFFFF9802
#define IA_MPEGH_DEC_EXE_FATAL_INVALID_TNS_SFB 0xFFFF9803
#define IA_MPEGH_DEC_EXE_FATAL_NULL_PTR_SFB_INFO 0xFFFF9804
#define IA_MPEGH_DEC_EXE_FATAL_UNSUPPORTED_NUM_CHANNELS 0xFFFF9805
#define IA_MPEGH_DEC_EXE_FATAL_INVALID_STEREO_CONF_COMB 0xFFFF9806
#define IA_MPEGH_DEC_EXE_FATAL_UNSUPPORTED_ELEM_INDEX 0xFFFF9807
#define IA_MPEGH_DEC_EXE_FATAL_INVALID_WINSHAPE_COMB 0xFFFF9808
#define IA_MPEGH_DEC_EXE_FATAL_NULL_PTR_LPD_DEC_HANDLE 0xFFFF9809
#define IA_MPEGH_DEC_EXE_FATAL_INVALID_PITCH_LAG 0xFFFF980A
#define IA_MPEGH_DEC_EXE_FATAL_INVALID_FD_FACTOR 0xFFFF980B
#define IA_MPEGH_DEC_EXE_FATAL_INVALID_PITCH 0xFFFF980C
#define IA_MPEGH_DEC_EXE_FATAL_MAX_DMX_MATRIX_ELEMENTS_EXCEEDED 0xFFFF980D
#define IA_MPEGH_DEC_EXE_FATAL_MAX_NUM_MC_BANDS_EXCEEDED 0xFFFF980E
#define IA_MPEGH_DEC_EXE_FATAL_NULL_PTR_COEF 0xFFFF980F
#define IA_MPEGH_DEC_EXE_FATAL_INVALID_PRESET_ID 0xFFFF9810
#define IA_MPEGH_DEC_EXE_FATAL_NO_SUITABLE_TRACK 0xFFFF9811
#define IA_MPEGH_DEC_EXE_FATAL_MCT_PROCESS_FAIL 0xFFFF9812
#define IA_MPEGH_DEC_EXE_FATAL_INVALID_CHAN_CONFIG 0xFFFF9813
#define IA_MPEGH_DEC_EXE_FATAL_UNSUPPORTED_MHAS_PKT_TYPE 0xFFFF9814
#define IA_MPEGH_DEC_EXE_FATAL_UNSUPPORTED_NUM_PRE_ROLLS 0xFFFF9815
#define IA_MPEGH_DEC_EXE_FATAL_DECODE_FRAME_ERROR 0xFFFF9816
#define IA_MPEGH_DEC_EXE_FATAL_MDP_PROCESS_ERROR 0xFFFF9817
#define IA_MPEGH_DEC_EXE_FATAL_ARITH_DECODE_FAILED 0xFFFF9818
#define IA_MPEGH_DEC_EXE_FATAL_INVALID_FSCALE 0xFFFF9819
#define IA_MPEGH_DEC_EXE_FATAL_UNSUPPORTED_SFB_INDEX 0xFFFF981A
#define IA_MPEGH_DEC_EXE_FATAL_INVALID_START_BAND 0xFFFF981B
#define IA_MPEGH_DEC_EXE_FATAL_MAX_ASSIGNED_GRP_IDS_EXCEEDED 0xFFFF981C
#define IA_MPEGH_DEC_EXE_FATAL_INVALID_GRP_ID 0xFFFF981D
#define IA_MPEGH_DEC_EXE_FATAL_INVALID_FAC_LEN 0xFFFF981E
#define IA_MPEGH_DEC_EXE_FATAL_INVALID_MAX_SFB 0xFFFF981F
#define IA_MPEGH_DEC_EXE_FATAL_INVALID_PROFILE_CONFIG 0xFFFF9820
#define IA_MPEGH_DEC_EXE_FATAL_NULL_PTR_TD_CFG_HANDLE 0xFFFF9821
#define IA_MPEGH_DEC_EXE_FATAL_NULL_PTR_UNI_DRC_COEF 0xFFFF9822
#define IA_MPEGH_DEC_EXE_FATAL_INVALID_SF 0xFFFF9823
#define IA_MPEGH_DEC_EXE_FATAL_SFB_EXCEEDED_MAX 0xFFFF9824
#define IA_MPEGH_DEC_EXE_FATAL_DOMAIN_SWITCHER_PROCESS_FAILED 0xFFFF9825
#define IA_MPEGH_DEC_EXE_FATAL_UNSUPPORTED_COMPATIBLE_PROFILE 0xFFFF9826

// DRC
#define IA_MPEGD_DRC_EXE_FATAL_INVALID_INDEX 0xFFFF9900
#define IA_MPEGD_DRC_EXE_FATAL_PROCESS_FAIL 0xFFFF9901
#define IA_MPEGD_DRC_UNSUPPORTED_SUBBAND_DOMAIN_MODE 0xFFFF9902

// HOA
#define IA_MPEGH_HOA_EXE_FATAL_SPATIAL_PROCESS_FAILED 0xFFFF9A00
#define IA_MPEGH_HOA_EXE_FATAL_SCRATCH_NULL 0xFFFF9A01
#define IA_MPEGH_HOA_EXE_FATAL_INVALID_HOA_CODED_GAIN 0xFFFF9A02


// BRIR
#define IA_MPEGH_BINAURAL_EXE_FATAL_UNSUPPORTED_SPEAKERS 0xFFFF9B00
#define IA_MPEGH_BINAURAL_EXE_FATAL_UNSUPPORTED_CHANNELS 0xFFFF9B01
#define IA_MPEGH_BINAURAL_EXE_FATAL_UNSUPPORTED_DATA_FORMAT 0xFFFF9B02
#define IA_MPEGH_BINAURAL_EXE_FATAL_COMPUTE_FILTER_PARAMETER_FAIL 0xFFFF9B03
#define IA_MPEGH_BINAURAL_EXE_FATAL_UNSUPPORTED_TAPS 0xFFFF9B04
#define IA_MPEGH_BINAURAL_EXE_FATAL_UNSUPPORTED_FILTER_LENGTH 0xFFFF9B05

// OAM
#define IA_MPEGH_OAM_EXE_FATAL_UNSUPPORTED_OBJ_MD_DECODING 0xFFFF9D00
#define IA_MPEGH_OAM_EXE_FATAL_UNSUPPORTED_FRAMELENGTH 0xFFFF9D01

// MAE preprocessor
#define IA_MPEGH_MAE_EXE_FATAL_DIVERGENCE_ERROR 0xFFFF9E00
#define IA_MPEGH_MAE_EXE_FATAL_INVALID_OAM_INDEX 0xFFFF9E01
#define IA_MPEGH_MAE_EXE_FATAL_INTERACTIVITY_VIOLATION 0xFFFF9E02
#define IA_MPEGH_MAE_EXE_FATAL_NO_DIFFUSION 0xFFFF9E03
#define IA_MPEGH_MAE_EXE_FATAL_UNSUPPORTED_ELEVATION_RANGE 0xFFFF9E04
#define IA_MPEGH_MAE_EXE_FATAL_UNSUPPORTED_AZIMUTH 0xFFFF9E05
#define IA_MPEGH_MAE_EXE_FATAL_UNSUPPORTED_GROUP_PRESET 0xFFFF9E06
#define IA_MPEGH_MAE_EXE_FATAL_ASI_NUM_GROUP_DIFFER 0xFFFF9E07
#define IA_MPEGH_MAE_EXE_FATAL_SWITCH_GROUP_OFF 0xFFFF9E08
#define IA_MPEGH_MAE_EXE_FATAL_ON_OFF_INTERACT_FAILED 0xFFFF9E09

#endif /* IMPEGHD_ERROR_CODES_H */
